//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMICYEAR
    {
        public ACADEMICYEAR()
        {
            this.SEMESTERs = new HashSet<SEMESTER>();
        }
    
        public string ID_ACADEMICYEAR { get; set; }
        public int ID_YEAR { get; set; }
        public string ACADEMICNAME { get; set; }
    
        public virtual YEAR YEAR { get; set; }
        public virtual ICollection<SEMESTER> SEMESTERs { get; set; }
    }
}
