//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATETYPE
    {
        public CANDIDATETYPE()
        {
            this.STUDENTs = new HashSet<STUDENT>();
        }
    
        public string ID_CANDIDATE { get; set; }
        public string CANDIDATENAME { get; set; }
    
        public virtual ICollection<STUDENT> STUDENTs { get; set; }
    }
}
