//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATEPROFILE
    {
        public int ID_CANDIDATEPROFILE { get; set; }
        public string CANDIDATE_PROFILE_NAME { get; set; }
        public Nullable<int> ID_STUDENT { get; set; }
        public Nullable<int> ID_PROFILE { get; set; }
    
        public virtual PROFILETYPE PROFILETYPE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
