//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public int ID_STUDENT { get; set; }
        public Nullable<double> MATH { get; set; }
        public Nullable<double> LITERATURE { get; set; }
        public Nullable<double> INTERVIEW { get; set; }
        public Nullable<double> ENGLIST { get; set; }
        public string GRADE_COMMENT { get; set; }
        public string RESULT { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
