//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QLSaiGonTech : DbContext
    {
        public DB_QLSaiGonTech()
            : base("name=DB_QLSaiGonTech")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACADEMICYEAR> ACADEMICYEARs { get; set; }
        public DbSet<CANDIDATEPROFILE> CANDIDATEPROFILEs { get; set; }
        public DbSet<CANDIDATETYPE> CANDIDATETYPEs { get; set; }
        public DbSet<COURSE> COURSEs { get; set; }
        public DbSet<EDUCATION> EDUCATIONs { get; set; }
        public DbSet<INPUT> INPUTs { get; set; }
        public DbSet<INTAKE> INTAKES { get; set; }
        public DbSet<PROFILETYPE> PROFILETYPEs { get; set; }
        public DbSet<SEMESTER> SEMESTERs { get; set; }
        public DbSet<STAGE> STAGEs { get; set; }
        public DbSet<STATUS> STATUS { get; set; }
        public DbSet<STUDENT> STUDENTs { get; set; }
        public DbSet<STUDYPROGRAM> STUDYPROGRAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<YEAR> YEARS { get; set; }
    }
}
