//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTAKE
    {
        public INTAKE()
        {
            this.STAGEs = new HashSet<STAGE>();
            this.STUDENTs = new HashSet<STUDENT>();
        }
    
        public string ID_INTAKES { get; set; }
        public Nullable<int> INTAKENAME { get; set; }
    
        public virtual ICollection<STAGE> STAGEs { get; set; }
        public virtual ICollection<STUDENT> STUDENTs { get; set; }
    }
}
