//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILETYPE
    {
        public PROFILETYPE()
        {
            this.CANDIDATEPROFILEs = new HashSet<CANDIDATEPROFILE>();
        }
    
        public int ID_PROFILE { get; set; }
        public int ID_INPUT { get; set; }
        public int ID_STATUS { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string VIETNAMESE_NAME { get; set; }
        public Nullable<int> SEQUENCE_NUM { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<CANDIDATEPROFILE> CANDIDATEPROFILEs { get; set; }
        public virtual INPUT INPUT { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
