//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTER
    {
        public SEMESTER()
        {
            this.STAGEs = new HashSet<STAGE>();
        }
    
        public string ID_SEMESTER { get; set; }
        public string ID_ACADEMICYEAR { get; set; }
        public string SEMESTER_NAME { get; set; }
    
        public virtual ACADEMICYEAR ACADEMICYEAR { get; set; }
        public virtual ICollection<STAGE> STAGEs { get; set; }
    }
}
