//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE
    {
        public string ID_STAGE { get; set; }
        public string ID_SEMESTER { get; set; }
        public string ID_INTAKES { get; set; }
        public string STAGENAME { get; set; }
        public Nullable<System.DateTime> ADMISSIONS_DATE { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public string EXAM_TIME { get; set; }
        public string TIMEOFENGLISHEXAM { get; set; }
    
        public virtual INTAKE INTAKE { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
    }
}
