//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSaiGonTechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.CANDIDATEPROFILEs = new HashSet<CANDIDATEPROFILE>();
        }
    
        public string ID_EDUCATION { get; set; }
        public string ID_INTAKES { get; set; }
        public string ID_CADIDATE { get; set; }
        public string ID_PROGRAM { get; set; }
        public int ID_STUDENT { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string GENDER { get; set; }
        public string PHONE { get; set; }
        public string WARDS { get; set; }
        public string DISTRICT { get; set; }
        public string PROVINCE { get; set; }
        public string NATION { get; set; }
        public string PLACEOFBIRTH { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string HOMEPHONE { get; set; }
        public string HIGHSCHOOLNAME { get; set; }
        public string HIGHSCHOOLCITY { get; set; }
        public Nullable<System.DateTime> GRADUATEYEAR { get; set; }
        public string HOMECOUNTRY { get; set; }
        public Nullable<System.DateTime> REGISTRYDATE { get; set; }
    
        public virtual ICollection<CANDIDATEPROFILE> CANDIDATEPROFILEs { get; set; }
        public virtual CANDIDATETYPE CANDIDATETYPE { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual EDUCATION EDUCATION { get; set; }
        public virtual INTAKE INTAKE { get; set; }
        public virtual STUDYPROGRAM STUDYPROGRAM { get; set; }
    }
}
